version: '4.30.0'

services:
  technest-pg:
    container_name: technest_docker1
    image: postgres
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/;lib/postgresql
    environment:
#      POSTGRES_USER: technest
      POSTGRES_PASSWORD: password
    networks:
      - technest
  adminer:
    image: adminer
    ports:
      - "8076:8080"
    networks:
      - technest

#      POSTGRES_DB: technest
#      PGDATA: /data/postgres


volumes:
  db_data: {}
networks:
  technest: